### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by djdjoko** [Jongchan/tensorflow-vdsr#6]
Would you be able to comment on how fast your implementation is for upscaling? How long do you need to upscale any of the test set images?

**Comment by Jongchan** [comment]
Running time for this algorithm is **0.075 seconds for 252x252 --> 504x504** with NVidia GTX 1080.
There are some issues that you should keep in mind:
* There's extra overhead for preprocessing (bicubic upscale) and model loading. The reported number above is **only** for the algorithm.
* The first run takes longer time, probably due to the CUDA implementation issue.
